language: node_js
node_js:
  - "20"

services:
  - docker

cache:
  directories:
    - "Backend/node_modules"
    - "FrontEnd/node_modules"

install:
  - cd Backend && npm ci && cd ..
  - cd FrontEnd && npm ci && cd ..

script:
  - cd Backend
  - npm run lint || true
  - npm run test
  - cd ..

  - cd FrontEnd
  - npm run lint
  - cd ..
  
  - docker-compose -f docker-compose.yml build
