version: '3.8'

services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: climacolombia-jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      # Mapeo del socket para Docker-out-of-Docker
      - //var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins_home:
